/* Modelagem Básica - 

ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE 

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LÓGICA - PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANDO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTAR AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA CLIENTE */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENEDERECO VARCHAR(100)
); 


/* VERIFICAR TABELAS NO BANCO */

SHOW TABLES;

/* DESCOBRINDO ESTRUTURA DA TABELA */

DESC CLIENTE;

/* SINTAXE DE INSERCAO - INSERT INTO TABELA... */

/*FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('MARIANA','F','MARIANA@GMAIL.COM',00000000000,'1135919991','RUA MATIAS');

/* FORMA 02 - DESCREVENDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENEDERECO, TELEFONE, CPF) VALUES('DANIEL','M','RUA LINDO','1123232',41660883855);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYQSL */

INSERT INTO CLIENTE VALUES('DANIEL','M','RUA LINDO','1123232',41660883855),
									('DANIEL','M','RUA LINDO','1123232',41660883855);
									
/* COMANDO SELECT - SELECAO, PROJECAO E JUNCAO */

SELECT NOW() AS DATA_HORA, 'DANIEL GOMES' AS PROFESSOR;	

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';								

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE; //PROJECAO

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE; //SELECAO

SELECT NOME, SEXO, EMAIL, NOW() AS DATA_HORA FROM CLIENTE; //JUNCAO 

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE; //TRAZ TODOS OS DADOS DA TABELA

/* FILTRANDO TABELA USANDO WHERE(ONDE) */

SELECT NOME, SEXO FROM CLIENTE 
WHERE SEXO = 'M';

/* UTILIZANDO O LIKE PARA TRAZER APROXIMACOES */

SELECT NOME, SEXO FROM CLIENTE WHERE ENEDERECO LIKE 'LINDO';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE WHERE ENEDERECO LIKE '%LINDO';

/* CONTANDO REGISTROS DA TABELA */

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TAB. CLIENTE" FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;
















